name: run-algorithm-tests
on: 
  pull_request:
jobs:
  run-algorithm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd gui && npm install && npm run test
